### ISSUE TITLE
vulnix --system doesn't work when run as unprivileged user

### ISSUE THREAD

**Issue by basvandijk** [flyingcircusio/vulnix#13]
My NixOS system apparently doesn't have the `/nix/var/nix/current-system` directory:

```
$ vulnix --system
error: getting status of ‘/nix/var/nix/current-system’: No such file or directory
```

Maybe vulnix should try `/nix/var/nix/profiles/system` if that previous directory can't be found.

Similarly user-mode also doesn't work:

```
$ vulnix --user
error: getting status of ‘/home/bas.van.dijk/.nix-profile/pkgs’: No such file or directory
```

**Comment by ckauhaus** [comment]
User mode is currently broken, this is a known issue. We're working on it.

W.r.t. current-system: this is interesting - we thought we could depend on /nix/var/nix/current-system... I'll get that fixed, too.

**Comment by ckauhaus** [comment]
The broken user mode will be handled separately in #8

**Comment by adisbladis** [comment]
This seems to no longer be the case. `vulnix --system` as an unprivileged user works fine.

**Comment by ckauhaus** [comment]
I'm going to check it - I think we fixed it without closing the ticket...

**Comment by ckauhaus** [comment]
`vulnix --system` should work on recent NixOS system when invoked as unprivileged user. Closing this issue.
