### ISSUE TITLE
Improve caching

### ISSUE THREAD

**Issue by ckauhaus** [flyingcircusio/vulnix#2]
- The parsing results should be cached.
- Caching should go into into ~/.vulnix (overridable by an envvar)

**Comment by ckauhaus** [comment]
Pro: vulnix now caches the pickles. 
Con: vulnix keeps the unzipped XML files around. It would be better to keep the gzipped XML files instead.

**Comment by plumps** [comment]
random

**Comment by plumps** [comment]
@ckauhaus
