### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by ctheune** [flyingcircusio/vulnix#22]
In our machines I see RAM usage with more than 1.5GiB while running vulnix. This is problematic as we support VMs with only 1GiB that customers want to use for something _useful_. This means quality of service suffers while vulnix is running. :(

**Comment by plumps** [comment]
Maybe cgroups (carried out by systemd) ressource management, limiting cpu / memory could be an approach.

**Comment by ctheune** [comment]
Uhm. Well. No. :) The RAM is needed by the program at the moment. Limiting it will cause it to crash. Need to review where the memory goes. I'm pretty sure we keep too many copies of data around and can optimize this with an hour or two of effort.

**Comment by ckauhaus** [comment]
Fixed in 8793c89 (forgot to close the ticket)
