### ISSUE TITLE
Latest release is outdated

### ISSUE THREAD

**Issue by mboelen** [flyingcircusio/vulnix#40]
When using the latest release, it points to 1.0.0. Can you update it so it points to the last version of the software?

Reference link: https://github.com/flyingcircusio/vulnix/releases/latest

**Comment by ckauhaus** [comment]
The release page on https://github.com/flyingcircusio/vulnix/releases is now correct. The newest release is also available on https://pypi.org/project/vulnix/ and in the nixpkgs tree.
