### ISSUE TITLE
Allow whitelisting a CVE "terminally"

### ISSUE THREAD

**Issue by ctheune** [flyingcircusio/vulnix#45]
Some CVEs exist but may be retracted, disputed, without patches or not be patched on purpose from our side. I'd like to mark whitelist entries in a way that results in the Vulnix exit code returning to "green".

**Comment by ckauhaus** [comment]
Changed exit code logic so that exit code 1 is only returned when `--show-whitelisted` is set. So if no whitelisted entries are printed, they are also not signalled via the exit code.

I think this is more consistent with users' expectations.
