### ISSUE TITLE
flake8 failure on latest master nixpkgs

### ISSUE THREAD

**Issue by delroth** [flyingcircusio/vulnix#46]
```
=================================== FAILURES ===================================
_________________________________ FLAKE8-check _________________________________
/build/vulnix-1.7.1/src/vulnix/output.py:128:9: E117 over-indented
```

**Comment by delroth** [comment]
Are you planning to do a release or should we just add the patch to nixpkgs? Currently vulnix doesn't build on master, I'd like to get it working again :-)

**Comment by ckauhaus** [comment]
I'll gonna release a new version at the end of this week. Want to get some bugfixes in.

**Comment by delroth** [comment]
Cool, looking forward to it!

**Comment by ckauhaus** [comment]
@delroth https://github.com/NixOS/nixpkgs/pull/57132
