### ISSUE TITLE
Add CVSS score(s) to the opened issues

### ISSUE THREAD

**Issue by Ekleog** [flyingcircusio/vulnix#53]
Hey! I'm not really sure I'm opening the feature request at the right place, but hope I did :)

I was thinking it'd be great to show the CVSS score alongside each of the issue lines in eg. [this issue](https://github.com/NixOS/nixpkgs/issues/64176), to allow for easier categorization of “important” issues.

For instance, I'm receiving an email for each vulnerability roundup, and have to consciously click on each link to check whether it warrants immediate attention or could be acted upon some time later -- which I don't always do, especially when I'm in a hurry.

What do you think about this?

**Comment by ckauhaus** [comment]
Interesting feature. I'll have a look into this - sounds doable.
