### ISSUE TITLE
Wait rather than fail when lock is held

### ISSUE THREAD

**Issue by chkno** [flyingcircusio/vulnix#60]
Running two instances of vulnix at the same time fails with this error:
```
zc.lockfile.LockError: Couldn't lock '/home/user/.cache/vulnix/Data.fs.lock'
```

`vulnix` should wait for the lock to become available rather than failing.  (This is what `nix` does.)

In particular, it would allow vulnix runs to be easily diffed against one another with `diff <(vulnix ...) <(vulnix ...)`, which is valuable for confirming that a contemplated change has the desired effect.  Practical example:

```
$ nixos-rebuild build -I nixos-config="$PWD/configuration.nix"
$ vulns() { vulnix --whitelist ~/nixos-vulnerability-roundup/whitelists/nixos-19.09.toml "$@" | sed -r 's,/nix/store/[^/]{32},/nix/store/...,g'; }
$ diff -u <(vulns --system) <(vulns ./result)
```

**Comment by ckauhaus** [comment]
Good point. Will look into this.
