### ISSUE TITLE
Feature request: Mention package maintainers

### ISSUE THREAD

**Issue by primeos** [flyingcircusio/vulnix#63]
IMO it would be nice if the GitHub issues (e.g. https://github.com/NixOS/nixpkgs/issues/88295) would also mention the maintainers so that they can have a look. Are there reasons against this or is it just not implemented yet?

**Comment by ckauhaus** [comment]
That should be doable. Currently figuring out what to include in vulnix proper and what to put into the driver tooling.

**Comment by ckauhaus** [comment]
Will have it ready for the next vulnerability roundup

**Comment by ckauhaus** [comment]
I did not get this into vulnix proper but have it in the surrounding driver code. The main reason is that vulnix looks only into .drv files which lack this piece of information. But I think having it in the driver code is ok. Example issue: https://github.com/NixOS/nixpkgs/issues/90851
