### ISSUE TITLE
Move /tmp/nvd to something more sensible

### ISSUE THREAD

**Issue by ckauhaus** [flyingcircusio/vulnix#7]
Writing into a file with a predictable name in a 777 directory (possibly as privileged user) is a huge security risk. This also runs into problems if both a privileged user and a non-privileged user use vulnix on the same system.

Better use a user-specific cache directory. Click has some support for [system-independent config directory access](http://click.pocoo.org/6/utils/#finding-application-folders), perhaps we can build on top of that. Or just use `$HOME/.cache/vulnix`.

**Comment by plumps** [comment]
Went for $HOME/.cache/vulnix
